# SPDX-FileCopyrightText: 2017-2020 Jens Lechtenbörger
# SPDX-License-Identifier: CC0-1.0

image: registry.gitlab.com/bhugueney/docker/emacs-scimax:custom-scimax-oxipynb

pages:
  stage: build
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - tlmgr init-usertree
  - emacs --batch --load elisp/publish.el
#  - cp public/howto.html public/index.html
  artifacts:
    paths:
    - public
    expire_in: 4 weeks
  only:
  - master

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git config --global user.email "${CI_EMAIL}"
    - git config --global user.name "${CI_USERNAME}"
    - git add public # Force add PDF since we .gitignored it
    - git commit -m "Generated ipynb from $CI_COMMIT_SHORT_SHA [skip ci]" || echo "No changes, nothing to commit!"
    - git remote rm origin && git remote add origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git push origin HEAD:$CI_COMMIT_REF_NAME # Pushes to the same branch as the trigger
